### ISSUE TITLE
Sample application code in docs

### ISSUE THREAD

**Issue by imanghafoori1** [rogervila/laravel-email-failer#9]
Hi,
Could you please provide some sample application code in the readme file ?
I mean the code we want to have tests for it.
Thanks in advance

**Comment by rogervila** [comment]
Hello @imanghafoori1 

I will try to provide a better example. 

Thank you for the suggestion.

**Comment by imanghafoori1** [comment]
👍 nice

**Comment by rogervila** [comment]
The current [provided example](https://github.com/rogervila/laravel-email-failer?tab=readme-ov-file#usage) should make it easier to understand.
